services:
  postgres_db:
    container_name: db
    image: postgres:15.0
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 8s
      timeout: 4s
      retries: 5
    ports: 
      - 5432:5432
  backend:
    container_name: carbonzero-data-management-be
    build:
      context: ../carbonzero_data_management
      dockerfile: ../carbonzero_data_management/Dockerfile.prod
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 8000
    volumes:
      - static:/carbonzero-data-management/static
    restart: always
    image: carbonzero-data-management-be
    depends_on:
      postgres_db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static
    depends_on:
      - postgres_db
      - backend
volumes:
  pgdata:
  static: